### PR TITLE
Fix typos + minor rephrasing

### PR DESCRIPTION
**Pull request by slel**

### CODE REVIEW

**Comment by slel** [comment]
Just realized I sent this pull request to the wrong repository. Ignore it.
I have now sent it to the ipython-website repository.

**Comment by slel** [comment]
Another thing: the short description for the `ipython/ipython.github.com` repository reads

>  Auto-generated sphinix version of the IPython website

Should this be 'sphinx' instead of 'sphinix'?

**Comment by Carreau** [comment]
> Should this be 'sphinx' instead of 'sphinix'?

Yep, fixed. 

Sorry for the PR on the wrong repo...

**Comment by Carreau** [comment]
Closed by ipython/ipython-website#98 ! 

Thanks !

**Pull request closed without merging**
